spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/income_processing_db_dev
  jpa:
    show-sql: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}

logging:
  level:
    com.sih: DEBUG
    org.springframework.web: DEBUG

